$('document').ready(function() {

    $('#main-header').show()
    $('#login').hide()
    $('#text-box').show()
    $('#register').hide()
    $('#todo-list-header').hide()
    $('#todo-table').hide()
    $('#create-todo').hide()
    $('#edit-todo').hide()
    $('#weather').show()
    $('#footer').show()

    $('#link-login').on('click', (event) => {
        event.preventDefault()
        $('#main-header').show()
        $('#login').show()
        $('#text-box').hide()
        $('#register').hide()
        $('#todo-list-header').hide()
        $('#todo-table').hide()
        $('#create-todo').hide()
        $('#edit-todo').hide()
        $('#weather').hide()
        $('#footer').show()
    })

    $('#link-register').on('click', (event) => {
        event.preventDefault()
        $('#main-header').show()
        $('#login').hide()
        $('#text-box').hide()
        $('#register').show()
        $('#todo-list-header').hide()
        $('#todo-table').hide()
        $('#create-todo').hide()
        $('#edit-todo').hide()
        $('#weather').hide()
        $('#footer').show()
    })

    $('#link-todos').on('click', (event) => {
        event.preventDefault()
        $('#main-header').hide()
        $('#login').hide()
        $('#text-box').hide()
        $('#register').hide()
        $('#todo-list-header').show()
        $('#todo-table').show()
        $('#create-todo').hide()
        $('#edit-todo').hide()
        $('#weather').show()
        $('#footer').show()
    })

    $('#link-edit').on('click', (event) => {
        event.preventDefault()
        $('#main-header').hide()
        $('#login').hide()
        $('#text-box').hide()
        $('#register').hide()
        $('#todo-list-header').show()
        $('#todo-table').hide()
        $('#create-todo').hide()
        $('#edit-todo').show()
        $('#weather').hide()
        $('#footer').show()
    })

    $('#link-delete').on('click', (event) => {
        event.preventDefault()
        $('#main-header').hide()
        $('#login').hide()
        $('#text-box').hide()
        $('#register').hide()
        $('#todo-list-header').show()
        $('#todo-table').show()
        $('#create-todo').hide()
        $('#edit-todo').hide()
        $('#weather').show()
        $('#footer').show()
    })
})